// Browser-side helper for the plugin e2e (served by the Vite dev server, imported from the page).
// Mounts L8 views directly, so the spec does not depend on the shell's markup, and teaches the mock
// IPC to install the real examples/plugins/hello-screen (preview generated by kelta-plugins tests).

import { mount, unmount } from 'svelte';

import * as samples from '$lib/gen/fixtures';
import type { PluginInstallPreview, ScreenOpenResult } from '$lib/gen';
import { getTransport, setTransport } from '$lib/ipc/transport';

import preview from './hello-screen.preview.json';

const hello = preview as unknown as PluginInstallPreview;
export const opened: ScreenOpenResult[] = [];

export function useHelloScreen(): void {
  const base = getTransport();
  setTransport({
    ...base,
    async invoke<T>(
      cmd: string,
      args?: Record<string, unknown> | Uint8Array,
      opts?: { headers?: Record<string, string> },
    ) {
      const a = (args ?? {}) as Record<string, unknown>;
      if (cmd === 'plugin_inspect') return structuredClone(hello) as T;
      if (cmd === 'plugin_install') {
        const m = hello.manifest;
        const info = {
          ...structuredClone(samples.pluginInfo),
          id: m.id,
          name: m.name,
          version: m.version,
          description: m.description,
          permissions: m.permissions,
          granted: a.grant as string[],
          contributes: m.contributes,
        };
        const state = window.__keltaMock!.state;
        state.plugins = [...state.plugins.filter((p) => p.id !== m.id), info];
        return structuredClone(info) as T;
      }
      const result = await base.invoke<T>(cmd, args, opts);
      if (cmd === 'plugin_screen_open') opened.push(result as ScreenOpenResult);
      return result;
    },
  });
}

/** Mounts a registry component into a fresh container; returns an unmount function. */
export async function mountView(
  load: () => Promise<{ default: unknown }>,
  props: Record<string, unknown>,
): Promise<() => void> {
  const { default: Component } = await load();
  const target = document.createElement('div');
  target.style.cssText = 'position:fixed;inset:0;z-index:100;background:var(--k-bg)';
  document.body.appendChild(target);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const app = mount(Component as any, { target, props });
  return () => {
    void unmount(app);
    target.remove();
  };
}
