//! Settings structs (SETTINGS.md). `#[serde(default, deny_unknown_fields)]` everywhere except
//! `plugins.*`. Schemas are generated by `xtask codegen` into `schema/*.schema.json`.
//!
//! Schema annotations (`x-kelta-*`) are emitted through `#[schemars(extend(...))]`.
//! Default `x-kelta-scope` is `["global","project"]` and is only written where it differs.

use std::collections::BTreeMap;
use std::path::PathBuf;

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::ext::{CommandDef, EmbedMode, ToolDef, TriggerDef};
use crate::ids::{AccountId, PluginId, ProjectId};
use crate::model::SplitDir;
use crate::secret::SecretRef;
use crate::tracker::StatusCategory;

/// Configuration layer (low → high precedence).
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize, TS, JsonSchema,
)]
#[serde(rename_all = "snake_case")]
pub enum Layer {
    Default,
    Plugin,
    Global,
    Project,
    Repo,
    Runtime,
}

// =============================================================================================
// Root
// =============================================================================================

/// Effective (merged) settings. Also the schema of the global `config.toml`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
#[schemars(title = "Kelta settings")]
pub struct Settings {
    #[schemars(extend("x-kelta-category" = "General", "x-kelta-order" = 0))]
    pub app: AppSettings,
    #[schemars(extend("x-kelta-category" = "Window", "x-kelta-order" = 1))]
    pub window: WindowSettings,
    #[schemars(extend("x-kelta-category" = "Keys", "x-kelta-order" = 2))]
    pub keys: KeysSettings,
    #[schemars(extend("x-kelta-category" = "Terminal", "x-kelta-order" = 3))]
    pub terminal: TerminalSettings,
    #[schemars(extend(
        "x-kelta-category" = "Linux graphics",
        "x-kelta-order" = 4,
        "x-kelta-scope" = ["global"],
        "x-kelta-restart" = true
    ))]
    pub linux: LinuxSettings,
    #[schemars(extend("x-kelta-category" = "Polling", "x-kelta-order" = 11))]
    pub polling: PollingSettings,
    #[schemars(extend("x-kelta-category" = "Notifications", "x-kelta-order" = 12))]
    pub notifications: NotificationSettings,
    #[schemars(extend("x-kelta-category" = "Claude", "x-kelta-order" = 7))]
    pub claude: ClaudeSettings,
    #[schemars(extend("x-kelta-category" = "Editors", "x-kelta-order" = 8))]
    pub editor: EditorSettings,
    #[schemars(extend(
        "x-kelta-category" = "Worktree & work",
        "x-kelta-order" = 9,
        "x-kelta-scope" = ["global", "project", "repo"]
    ))]
    pub worktree: WorktreeSettings,
    #[schemars(extend("x-kelta-category" = "Worktree & work", "x-kelta-order" = 9))]
    pub work: WorkSettings,
    #[schemars(extend("x-kelta-category" = "Reviews", "x-kelta-order" = 10))]
    pub reviews: ReviewsSettings,
    #[schemars(extend("x-kelta-category" = "Tools", "x-kelta-order" = 13))]
    pub web: WebSettings,
    #[schemars(extend("x-kelta-category" = "Performance", "x-kelta-order" = 16))]
    pub performance: PerformanceSettings,
    #[schemars(extend(
        "x-kelta-category" = "Accounts",
        "x-kelta-order" = 6,
        "x-kelta-scope" = ["global"]
    ))]
    pub accounts: BTreeMap<AccountId, AccountConfig>,
    #[schemars(extend(
        "x-kelta-category" = "Accounts",
        "x-kelta-order" = 6,
        "x-kelta-scope" = ["global"]
    ))]
    pub oauth: OAuthSettings,
    #[schemars(extend(
        "x-kelta-category" = "Worktree & work",
        "x-kelta-order" = 9,
        "x-kelta-scope" = ["global", "project", "repo"],
        "x-kelta-merge" = "by_id"
    ))]
    pub session_templates: Vec<SessionTemplate>,
    #[schemars(extend(
        "x-kelta-category" = "Tools",
        "x-kelta-order" = 13,
        "x-kelta-scope" = ["global", "project", "repo"],
        "x-kelta-merge" = "by_id",
        "x-kelta-exec" = true
    ))]
    pub tools: Vec<ToolDef>,
    #[schemars(extend(
        "x-kelta-category" = "Triggers",
        "x-kelta-order" = 14,
        "x-kelta-scope" = ["global", "project", "repo"],
        "x-kelta-merge" = "by_id",
        "x-kelta-exec" = true
    ))]
    pub triggers: Vec<TriggerDef>,
    #[schemars(extend(
        "x-kelta-category" = "Tools",
        "x-kelta-order" = 13,
        "x-kelta-scope" = ["global", "project", "repo"],
        "x-kelta-merge" = "by_id",
        "x-kelta-exec" = true
    ))]
    pub commands: Vec<CommandDef>,
    #[schemars(extend("x-kelta-category" = "Plugins", "x-kelta-order" = 15))]
    pub plugins: PluginsSettings,
    /// Environment added to every session of the project (project/repo files).
    #[schemars(extend(
        "x-kelta-category" = "Projects",
        "x-kelta-order" = 5,
        "x-kelta-scope" = ["global", "project", "repo"],
        "x-kelta-exec" = true
    ))]
    pub env: BTreeMap<String, String>,
}

// =============================================================================================
// [app] [window]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Theme {
    #[default]
    System,
    Dark,
    Light,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum RestoreMode {
    #[default]
    Lazy,
    Eager,
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum LogLevel {
    Error,
    Warn,
    #[default]
    Info,
    Debug,
    Trace,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct AppSettings {
    pub theme: Theme,
    /// Dormant session respawn policy.
    pub restore_mode: RestoreMode,
    /// Ask before quitting while Claude is working or waiting for you.
    pub confirm_quit_with_running: bool,
    #[schemars(extend("x-kelta-restart" = true, "x-kelta-scope" = ["global"]))]
    pub log_level: LogLevel,
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            theme: Theme::System,
            restore_mode: RestoreMode::Lazy,
            confirm_quit_with_running: true,
            log_level: LogLevel::Info,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Decorations {
    #[default]
    Auto,
    Native,
    None,
    Custom,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CloseBehavior {
    #[default]
    Auto,
    Background,
    Quit,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct WindowSettings {
    /// auto = none on Hyprland/Sway, native elsewhere.
    #[schemars(extend("x-kelta-restart" = true, "x-kelta-scope" = ["global"]))]
    pub decorations: Decorations,
    /// auto = background on macOS, quit on Linux.
    #[schemars(extend("x-kelta-scope" = ["global"]))]
    pub close_behavior: CloseBehavior,
    #[schemars(extend("x-kelta-scope" = ["global"]))]
    pub restore_geometry: bool,
}

impl Default for WindowSettings {
    fn default() -> Self {
        Self { decorations: Decorations::Auto, close_behavior: CloseBehavior::Auto, restore_geometry: true }
    }
}

// =============================================================================================
// [keys]
// =============================================================================================

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct KeysSettings {
    /// App-prefix chord or `"off"`.
    pub prefix: String,
    #[schemars(range(min = 200, max = 5000))]
    pub prefix_timeout_ms: u32,
    /// ActionId → chords. Overrides only: unlisted actions use the platform defaults of the
    /// ActionId catalog (`ui/src/lib/gen/actions.ts`); `[]` unbinds.
    pub bindings: BTreeMap<String, Vec<String>>,
    /// ActionId → single key after the prefix.
    pub prefix_bindings: BTreeMap<String, String>,
    /// Single-key shortcuts in lists/boards.
    pub list_keys: bool,
}

impl Default for KeysSettings {
    fn default() -> Self {
        Self {
            prefix: "ctrl+shift+space".into(),
            prefix_timeout_ms: 1000,
            bindings: BTreeMap::new(),
            prefix_bindings: crate::actions::default_prefix_bindings(),
            list_keys: true,
        }
    }
}

// =============================================================================================
// [terminal]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Renderer {
    #[default]
    Auto,
    Webgl,
    Dom,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CursorStyle {
    #[default]
    Block,
    Bar,
    Underline,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum OptionAsMeta {
    None,
    Left,
    Right,
    #[default]
    Both,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "kebab-case")]
pub enum Osc52 {
    Off,
    #[default]
    Write,
    ReadWrite,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum BellMode {
    #[default]
    Attention,
    Visual,
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "kebab-case")]
pub enum ShiftEnter {
    #[default]
    Passthrough,
    EscCr,
    Newline,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum KeyboardProtocol {
    #[default]
    Legacy,
}

/// Rust-model scrollback lines per session kind.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ScrollbackSettings {
    pub shell: u32,
    pub claude: u32,
    pub editor: u32,
    pub tool: u32,
    pub setup: u32,
    pub custom: u32,
}

impl Default for ScrollbackSettings {
    fn default() -> Self {
        Self { shell: 3000, claude: 3000, editor: 500, tool: 500, setup: 1000, custom: 3000 }
    }
}

impl ScrollbackSettings {
    /// Lines for a session kind name (`SessionKind::name()`).
    pub fn for_kind(&self, kind: &str) -> u32 {
        match kind {
            "shell" => self.shell,
            "claude" => self.claude,
            "editor" => self.editor,
            "tool" => self.tool,
            "setup" => self.setup,
            _ => self.custom,
        }
    }
}

/// Where terminal sessions live.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum SessionHost {
    /// PTYs in the app process: quitting ends them.
    Inprocess,
    /// PTYs in `keltad`: sessions survive quit and re-attach on the next start.
    #[default]
    Daemon,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct TerminalSettings {
    /// System fonts only.
    pub font_family: String,
    #[schemars(range(min = 6.0, max = 40.0))]
    pub font_size: f64,
    #[schemars(range(min = 1.0, max = 2.0))]
    pub line_height: f64,
    pub letter_spacing: f64,
    /// auto = webgl on macOS, dom on Linux.
    pub renderer: Renderer,
    pub cursor_style: CursorStyle,
    /// Focused pane only.
    pub cursor_blink: bool,
    pub scrollback: ScrollbackSettings,
    #[schemars(range(min = 100, max = 10000))]
    pub view_scrollback: u32,
    #[schemars(range(min = 1, max = 12))]
    pub max_live_views: u32,
    #[schemars(range(min = 32, max = 2048))]
    pub memory_cap_mb: u32,
    /// Append scrolled-off lines (plain text) to an on-disk log per session: search + restore.
    pub history_log: bool,
    /// Per-session log cap (two rotated halves).
    #[schemars(range(min = 1, max = 1024))]
    pub history_log_mb: u32,
    /// Cap of all session logs; oldest files are deleted first.
    #[schemars(range(min = 16, max = 65536))]
    pub history_log_total_mb: u32,
    /// macOS.
    pub option_as_meta: OptionAsMeta,
    pub copy_on_select: bool,
    /// Linux: select → PRIMARY, middle-click paste.
    pub primary_selection: bool,
    /// Only when bracketed paste is off.
    pub confirm_multiline_paste: bool,
    pub osc52: Osc52,
    pub bell: BellMode,
    /// Session kind name (or `default`) → Shift+Enter handling.
    pub shift_enter: BTreeMap<String, ShiftEnter>,
    pub keyboard_protocol: KeyboardProtocol,
    /// Empty = `$SHELL`.
    pub shell: String,
    #[schemars(extend("x-kelta-exec" = true))]
    pub env: BTreeMap<String, String>,
    pub minimum_contrast_ratio: f64,
    /// `daemon` = sessions survive quit (keltad).
    #[schemars(extend("x-kelta-restart" = true, "x-kelta-scope" = ["global"]))]
    pub session_host: SessionHost,
}

impl Default for TerminalSettings {
    fn default() -> Self {
        Self {
            font_family: "JetBrains Mono, Menlo, DejaVu Sans Mono, monospace".into(),
            font_size: 13.0,
            line_height: 1.15,
            letter_spacing: 0.0,
            renderer: Renderer::Auto,
            cursor_style: CursorStyle::Block,
            cursor_blink: false,
            scrollback: ScrollbackSettings::default(),
            view_scrollback: 1000,
            max_live_views: 2,
            memory_cap_mb: 160,
            history_log: true,
            history_log_mb: 16,
            history_log_total_mb: 512,
            option_as_meta: OptionAsMeta::Both,
            copy_on_select: false,
            primary_selection: true,
            confirm_multiline_paste: true,
            osc52: Osc52::Write,
            bell: BellMode::Attention,
            shift_enter: BTreeMap::from([
                ("claude".to_owned(), ShiftEnter::EscCr),
                ("default".to_owned(), ShiftEnter::Passthrough),
            ]),
            keyboard_protocol: KeyboardProtocol::Legacy,
            shell: String::new(),
            env: BTreeMap::new(),
            minimum_contrast_ratio: 1.0,
            session_host: SessionHost::Daemon,
        }
    }
}

// =============================================================================================
// [linux.graphics]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GraphicsProfile {
    #[default]
    Auto,
    Default,
    Safe,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GdkBackend {
    #[default]
    Auto,
    Wayland,
    X11,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct LinuxSettings {
    pub graphics: LinuxGraphics,
}

/// `[linux.graphics]`, read by `platform::pre_init` through `kelta_config::early::linux_graphics`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct LinuxGraphics {
    /// safe = all workarounds.
    pub profile: GraphicsProfile,
    /// NVIDIA proprietary → dmabuf off + explicit sync off.
    pub auto_nvidia: bool,
    /// `WEBKIT_DISABLE_DMABUF_RENDERER=1`.
    pub disable_dmabuf: bool,
    /// `WEBKIT_DISABLE_COMPOSITING_MODE=1`.
    pub disable_compositing: bool,
    /// `__NV_DISABLE_EXPLICIT_SYNC=1`.
    pub nvidia_disable_explicit_sync: bool,
    /// `GDK_BACKEND`.
    pub gdk_backend: GdkBackend,
}

impl Default for LinuxGraphics {
    fn default() -> Self {
        Self {
            profile: GraphicsProfile::Auto,
            auto_nvidia: true,
            disable_dmabuf: false,
            disable_compositing: false,
            nvidia_disable_explicit_sync: false,
            gdk_backend: GdkBackend::Auto,
        }
    }
}

// =============================================================================================
// [polling] [notifications]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum WhenClosed {
    #[default]
    Off,
    Background,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct PollingSettings {
    pub focused_secs: u32,
    /// Window unfocused; 0 = off.
    pub background_secs: u32,
    pub when_closed: WhenClosed,
    /// Redmine floor 60 enforced in code.
    #[schemars(range(min = 30))]
    pub min_secs: u32,
}

impl Default for PollingSettings {
    fn default() -> Self {
        Self { focused_secs: 120, background_secs: 600, when_closed: WhenClosed::Off, min_secs: 30 }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct NotificationSettings {
    pub enabled: bool,
    pub claude_needs_input: bool,
    pub claude_done: bool,
    /// Keeps review subscriptions polling in background.
    pub review_requested: bool,
    pub ci_failed_mine: bool,
    pub pr_approved: bool,
    pub pr_changes_requested: bool,
    pub bell_background: bool,
    /// Or pane hidden.
    pub only_when_unfocused: bool,
    /// `"HH:MM-HH:MM"` local time, or empty.
    pub quiet_hours: String,
}

impl Default for NotificationSettings {
    fn default() -> Self {
        Self {
            enabled: true,
            claude_needs_input: true,
            claude_done: true,
            review_requested: true,
            ci_failed_mine: true,
            pr_approved: true,
            pr_changes_requested: true,
            bell_background: false,
            only_when_unfocused: true,
            quiet_hours: String::new(),
        }
    }
}

// =============================================================================================
// [claude]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum HookTransport {
    #[default]
    Command,
    Http,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "lowercase")]
pub enum ClaudeEffort {
    Low,
    Medium,
    #[default]
    High,
    Xhigh,
    Max,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "camelCase")]
pub enum PermissionMode {
    Default,
    #[default]
    AcceptEdits,
    Plan,
    Auto,
    DontAsk,
    BypassPermissions,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ClaudeProfile {
    pub model: String,
    pub effort: ClaudeEffort,
    pub permission_mode: PermissionMode,
}

impl Default for ClaudeProfile {
    fn default() -> Self {
        Self {
            model: "opus".into(),
            effort: ClaudeEffort::High,
            permission_mode: PermissionMode::AcceptEdits,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ClaudeSettings {
    /// Resolved in the login PATH.
    #[schemars(extend("x-kelta-exec" = true))]
    pub binary: String,
    /// Semver; older → warning, hooks still attempted.
    pub min_version: String,
    /// SessionStart always uses a command hook.
    pub hook_transport: HookTransport,
    /// Kelta MCP server for Claude sessions.
    pub mcp: bool,
    /// Passed via `--allowedTools`.
    pub allowed_tools: Vec<String>,
    /// Appended to the generated `context.md`.
    #[schemars(extend("x-kelta-scope" = ["global", "project", "repo"]))]
    pub append_system_prompt: String,
    /// Appended before the prompt.
    #[schemars(extend("x-kelta-exec" = true))]
    pub extra_args: Vec<String>,
    /// Merged into the generated `--settings` hooks.
    #[schemars(extend("x-kelta-exec" = true))]
    pub extra_hooks: BTreeMap<String, serde_json::Value>,
    pub profiles: BTreeMap<String, ClaudeProfile>,
    pub prompt_templates: BTreeMap<String, String>,
    /// v0.2; ignored in v0.1.
    pub ide_bridge: bool,
}

impl Default for ClaudeSettings {
    fn default() -> Self {
        let plan = ClaudeProfile {
            model: "opus".into(),
            effort: ClaudeEffort::High,
            permission_mode: PermissionMode::Plan,
        };
        Self {
            binary: "claude".into(),
            min_version: "2.1.200".into(),
            hook_transport: HookTransport::Command,
            mcp: true,
            allowed_tools: vec!["mcp__kelta__*".into()],
            append_system_prompt: String::new(),
            extra_args: Vec::new(),
            extra_hooks: BTreeMap::new(),
            profiles: BTreeMap::from([
                ("default".to_owned(), ClaudeProfile::default()),
                ("review".to_owned(), plan.clone()),
                ("plan".to_owned(), plan),
            ]),
            prompt_templates: BTreeMap::from([
                (
                    "ticket".to_owned(),
                    "Work on {ticket.key}: {ticket.title}. The full ticket is in {run}/ticket.md. Read it, then propose a short plan before editing.".to_owned(),
                ),
                (
                    "review".to_owned(),
                    "Review PR {pr.url} ({pr.head} → {pr.base}). Focus on correctness, tests and risks. Do not edit files.".to_owned(),
                ),
                ("standalone".to_owned(), String::new()),
            ]),
            ide_bridge: false,
        }
    }
}

// =============================================================================================
// [editor]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum FollowEdits {
    Off,
    #[default]
    Reload,
    Open,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum EditorOpenMode {
    Rpc,
    Keys,
    Command,
    #[default]
    None,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum EditorRestore {
    Mksession,
    #[default]
    None,
}

/// Placeholders: `{sock}`, `{path}`, `{file}`, `{line}`, `{cwd}`, `{sid8}`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct EditorPreset {
    pub id: String,
    pub label: String,
    pub command: String,
    pub args: Vec<String>,
    pub open: EditorOpenMode,
    pub open_keys: Option<String>,
    pub open_cmd: Option<Vec<String>>,
    /// Launched outside Kelta (the template's editor pane becomes a shell).
    pub external: bool,
    pub restore: EditorRestore,
    pub enabled: bool,
}

impl Default for EditorPreset {
    fn default() -> Self {
        Self {
            id: String::new(),
            label: String::new(),
            command: String::new(),
            args: Vec::new(),
            open: EditorOpenMode::None,
            open_keys: None,
            open_cmd: None,
            external: false,
            restore: EditorRestore::None,
            enabled: true,
        }
    }
}

fn s(v: &str) -> String {
    v.to_owned()
}

fn sv(v: &[&str]) -> Vec<String> {
    v.iter().map(|x| (*x).to_owned()).collect()
}

/// SETTINGS §2.1.
pub fn default_editor_presets() -> Vec<EditorPreset> {
    vec![
        EditorPreset {
            id: s("nvim"),
            label: s("Neovim"),
            command: s("nvim"),
            args: sv(&["--listen", "{sock}", "{path}"]),
            open: EditorOpenMode::Rpc,
            restore: EditorRestore::Mksession,
            ..EditorPreset::default()
        },
        EditorPreset {
            id: s("vim"),
            label: s("Vim"),
            command: s("vim"),
            args: sv(&["{path}"]),
            open: EditorOpenMode::Keys,
            open_keys: Some(s("<C-\\><C-N>:edit +{line} {file}<CR>")),
            ..EditorPreset::default()
        },
        EditorPreset {
            id: s("helix"),
            label: s("Helix"),
            command: s("hx"),
            args: sv(&["{path}"]),
            open: EditorOpenMode::None,
            ..EditorPreset::default()
        },
        EditorPreset {
            id: s("emacs"),
            label: s("Emacs"),
            command: s("emacs"),
            args: sv(&[
                "-nw",
                "--eval",
                "(progn (setq server-name \"kelta-{sid8}\") (server-start))",
                "{path}",
            ]),
            open: EditorOpenMode::Command,
            open_cmd: Some(sv(&["emacsclient", "-s", "kelta-{sid8}", "-n", "+{line}", "{file}"])),
            ..EditorPreset::default()
        },
        EditorPreset {
            id: s("vscode"),
            label: s("VS Code"),
            external: true,
            command: s("code"),
            args: sv(&["{path}"]),
            open: EditorOpenMode::Command,
            open_cmd: Some(sv(&["code", "-g", "{file}:{line}"])),
            ..EditorPreset::default()
        },
        EditorPreset {
            id: s("zed"),
            label: s("Zed"),
            external: true,
            command: s("zed"),
            args: sv(&["{path}"]),
            open: EditorOpenMode::Command,
            open_cmd: Some(sv(&["zed", "{file}:{line}"])),
            ..EditorPreset::default()
        },
    ]
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct EditorSettings {
    /// Preset id.
    pub default: String,
    pub follow_claude_edits: FollowEdits,
    /// The diff editor's arguments: appended for review sessions and used by Review diff on own work
    /// items, e.g. `["-c","DiffviewOpen {range}"]` (`{range}` = `<remote>/<base>` for own items, merge
    /// base to working tree; `<remote>/<base>...HEAD` for review checkouts). Empty: `git diff` in a shell.
    #[schemars(extend("x-kelta-scope" = ["global", "project", "repo"]))]
    pub review_args: Vec<String>,
    #[schemars(extend("x-kelta-merge" = "by_id", "x-kelta-exec" = true))]
    pub presets: Vec<EditorPreset>,
}

impl Default for EditorSettings {
    fn default() -> Self {
        Self {
            default: "nvim".into(),
            follow_claude_edits: FollowEdits::Reload,
            review_args: Vec::new(),
            presets: default_editor_presets(),
        }
    }
}

// =============================================================================================
// [worktree] [work]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum Cleanup {
    #[default]
    Ask,
    Auto,
    Never,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct WorktreeSettings {
    /// Template; outside the repo.
    pub root: String,
    /// Validated with `git check-ref-format --branch`.
    pub branch_template: String,
    /// Issue type (lowercased) → `{type}`.
    pub type_map: BTreeMap<String, String>,
    pub slug_max: u32,
    /// Globs copied from the main checkout; `.worktreeinclude` patterns appended.
    pub include: Vec<String>,
    /// Each run in the visible setup pane.
    #[schemars(extend("x-kelta-exec" = true))]
    pub setup: Vec<String>,
    /// Claude waits for setup exit 0.
    pub setup_blocking: bool,
    pub fetch_timeout_secs: u32,
    pub cleanup: Cleanup,
}

impl Default for WorktreeSettings {
    fn default() -> Self {
        Self {
            root: "~/.kelta-worktrees/{project}/{repo}/{key}-{slug}".into(),
            branch_template: "{type}/{key}-{slug}".into(),
            type_map: BTreeMap::from([
                (s("bug"), s("fix")),
                (s("story"), s("feat")),
                (s("task"), s("feat")),
                (s("feature"), s("feat")),
                (s("default"), s("chore")),
            ]),
            slug_max: 40,
            include: sv(&[".env", ".env.*"]),
            setup: Vec::new(),
            setup_blocking: true,
            fetch_timeout_secs: 20,
            cleanup: Cleanup::Ask,
        }
    }
}

/// `{ category = "in_progress" }` or `{ name = "In Progress" }`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(untagged)]
pub enum TransitionTarget {
    Category { category: StatusCategory },
    Name { name: String },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct OnStart {
    pub assign_me: bool,
    pub transition_to: Option<TransitionTarget>,
    pub comment: Option<String>,
}

impl Default for OnStart {
    fn default() -> Self {
        Self {
            assign_me: true,
            transition_to: Some(TransitionTarget::Category { category: StatusCategory::InProgress }),
            comment: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct OnPr {
    pub transition_to: Option<TransitionTarget>,
    pub comment: Option<String>,
}

impl Default for OnPr {
    fn default() -> Self {
        Self {
            transition_to: Some(TransitionTarget::Category { category: StatusCategory::InReview }),
            comment: Some("PR: {pr.url}".into()),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct OnMerge {
    pub transition_to: Option<TransitionTarget>,
    pub offer_cleanup: bool,
}

impl Default for OnMerge {
    fn default() -> Self {
        Self {
            transition_to: Some(TransitionTarget::Category { category: StatusCategory::Done }),
            offer_cleanup: true,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct PrSettings {
    pub title_template: String,
    /// `{closes}` = `Closes #n` for GitHub issues.
    pub body_template: String,
    pub draft: bool,
}

impl Default for PrSettings {
    fn default() -> Self {
        Self {
            title_template: "{ticket.key}: {ticket.title}".into(),
            body_template: "{ticket.url}\n\n{closes}".into(),
            draft: false,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct WorkSettings {
    /// Show the StartWorkPlan sheet.
    pub plan_preview: bool,
    pub default_template: String,
    pub review_template: String,
    pub on_start: OnStart,
    pub on_pr: OnPr,
    pub on_merge: OnMerge,
    pub pr: PrSettings,
}

impl Default for WorkSettings {
    fn default() -> Self {
        Self {
            plan_preview: true,
            default_template: "claude+editor".into(),
            review_template: "review".into(),
            on_start: OnStart::default(),
            on_pr: OnPr::default(),
            on_merge: OnMerge::default(),
            pr: PrSettings::default(),
        }
    }
}

// =============================================================================================
// [reviews] [web] [performance]
// =============================================================================================

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ReviewsSettings {
    pub include_team_requests: bool,
    pub include_drafts: bool,
    /// Linked tickets regex over branch + title.
    pub ticket_key_regex: String,
    pub repos_allow: Vec<String>,
    pub repos_deny: Vec<String>,
}

impl Default for ReviewsSettings {
    fn default() -> Self {
        Self {
            include_team_requests: true,
            include_drafts: false,
            ticket_key_regex: "[A-Z][A-Z0-9]+-\\d+|#\\d+".into(),
            repos_allow: Vec::new(),
            repos_deny: Vec::new(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct WebSettings {
    pub embed_default: EmbedMode,
    /// Keep hidden iframes.
    pub keep_alive: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct PerformanceSettings {
    /// StatusBar memory HUD.
    pub hud: bool,
}

// =============================================================================================
// [accounts.<id>]
// =============================================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AccountKind {
    Jira,
    Redmine,
    Github,
    Gitlab,
    Linear,
    /// Bitbucket Cloud: code host only (its issue tracker was removed in August 2026).
    Bitbucket,
    /// Gitea / Forgejo (self-hosted, `base_url` required): issues and pull requests.
    Gitea,
}

impl AccountKind {
    pub fn is_code_host(self) -> bool {
        matches!(self, Self::Github | Self::Gitlab | Self::Bitbucket | Self::Gitea)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum JiraFlavor {
    #[default]
    Auto,
    Cloud,
    Dc,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum AuthKind {
    Basic,
    Bearer,
    ApiKey,
    Token,
    /// Bearer token from "Sign in with browser" (device flow), refreshed before it expires.
    Oauth,
}

/// OAuth apps used by "Sign in with browser" (device flow, GitHub and GitLab).
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct OAuthSettings {
    /// Client id of the GitHub OAuth App or application id of the GitLab application, per host (`github.com`, `gitlab.com`, `gitlab.acme.example`). Public values; a host without one only offers pasted tokens.
    pub client_ids: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize, TS, JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum TextFormat {
    #[default]
    Textile,
    Markdown,
}

/// One tracker / code-host account (global scope only).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct AccountConfig {
    pub kind: AccountKind,
    /// github: `https://api.github.com`; gitlab: `https://gitlab.com`; linear: `https://api.linear.app`; bitbucket: `https://api.bitbucket.org/2.0`; required for jira/redmine/gitea.
    #[serde(default)]
    pub base_url: Option<String>,
    #[serde(default)]
    pub flavor: JiraFlavor,
    /// Default per kind: jira cloud `basic`, dc `bearer`, redmine `api_key`, github/gitlab/gitea `token`, bitbucket `basic` (account `email` + API token; `bearer` for repository/workspace access tokens), linear raw API key (`bearer` for OAuth).
    #[serde(default)]
    pub auth: Option<AuthKind>,
    #[serde(default)]
    pub email: Option<String>,
    #[serde(default)]
    pub user: Option<String>,
    /// Default github `gh-cli`, gitlab `glab-cli`.
    #[serde(default)]
    #[schemars(extend("x-kelta-secret" = true))]
    pub secret: Option<SecretRef>,
    #[serde(default)]
    pub text_format: TextFormat,
    #[serde(default)]
    pub poll_secs: Option<u32>,
    /// Browser links (GHE/GitLab); derived when absent.
    #[serde(default)]
    pub web_url: Option<String>,
}

impl AccountConfig {
    /// `base_url` with per-kind defaults.
    pub fn effective_base_url(&self) -> Option<String> {
        self.base_url.clone().or_else(|| match self.kind {
            AccountKind::Github => Some("https://api.github.com".into()),
            AccountKind::Gitlab => Some("https://gitlab.com".into()),
            AccountKind::Linear => Some("https://api.linear.app".into()),
            AccountKind::Bitbucket => Some("https://api.bitbucket.org/2.0".into()),
            _ => None,
        })
    }

    /// `secret` with per-kind defaults.
    pub fn effective_secret(&self) -> Option<SecretRef> {
        self.secret.clone().or_else(|| match self.kind {
            AccountKind::Github => Some(SecretRef::new("gh-cli")),
            AccountKind::Gitlab => Some(SecretRef::new("glab-cli")),
            _ => None,
        })
    }
}

// =============================================================================================
// [[session_templates]]
// =============================================================================================

/// `{ split = "row", ratios = [..], children = [..] }` | `{ session = "claude", ... }`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(untagged)]
pub enum TemplateNode {
    Split {
        split: SplitDir,
        ratios: Vec<f32>,
        children: Vec<TemplateNode>,
    },
    Session {
        /// `claude` | `editor` | `shell` | `setup` | `tool:<id>`.
        session: String,
        #[serde(default)]
        name: Option<String>,
        /// Claude profile.
        #[serde(default)]
        profile: Option<String>,
        /// Shell: run this then stay interactive.
        #[serde(default)]
        command: Option<String>,
    },
}

impl Default for TemplateNode {
    fn default() -> Self {
        Self::session("shell")
    }
}

impl TemplateNode {
    pub fn session(kind: &str) -> Self {
        Self::Session { session: kind.to_owned(), name: None, profile: None, command: None }
    }
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct SessionTemplate {
    pub id: String,
    pub label: String,
    pub layout: TemplateNode,
    pub enabled: bool,
}

impl Default for SessionTemplate {
    fn default() -> Self {
        Self { id: String::new(), label: String::new(), layout: TemplateNode::default(), enabled: true }
    }
}

/// SETTINGS §2 defaults.
pub fn default_session_templates() -> Vec<SessionTemplate> {
    let t = |id: &str, label: &str, layout: TemplateNode| SessionTemplate {
        id: id.to_owned(),
        label: label.to_owned(),
        layout,
        enabled: true,
    };
    vec![
        t(
            "claude+editor",
            "Claude + editor",
            TemplateNode::Split {
                split: SplitDir::Row,
                ratios: vec![0.5, 0.5],
                children: vec![TemplateNode::session("claude"), TemplateNode::session("editor")],
            },
        ),
        t(
            "review",
            "Review",
            TemplateNode::Split {
                split: SplitDir::Row,
                ratios: vec![0.5, 0.5],
                children: vec![
                    TemplateNode::Session {
                        session: s("claude"),
                        name: None,
                        profile: Some(s("review")),
                        command: None,
                    },
                    TemplateNode::Split {
                        split: SplitDir::Column,
                        ratios: vec![0.75, 0.25],
                        children: vec![
                            TemplateNode::session("editor"),
                            TemplateNode::Session {
                                session: s("shell"),
                                name: None,
                                profile: None,
                                command: Some(s("git diff --stat origin/{base}...HEAD")),
                            },
                        ],
                    },
                ],
            },
        ),
        t("claude", "Claude", TemplateNode::session("claude")),
        t("editor", "Editor", TemplateNode::session("editor")),
        t("shell", "Shell", TemplateNode::session("shell")),
    ]
}

// =============================================================================================
// [plugins]
// =============================================================================================

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default)]
pub struct PluginsSettings {
    /// Unpacked plugin dirs loaded in dev mode (global only; still require grants).
    #[schemars(extend("x-kelta-scope" = ["global"]))]
    pub dev_paths: Vec<PathBuf>,
    pub disabled: Vec<PluginId>,
    /// `plugins.<id>` tables validated against each plugin's settings schema.
    #[serde(flatten)]
    pub settings: BTreeMap<String, serde_json::Value>,
}

// =============================================================================================
// Default for root (needs the helper fns above)
// =============================================================================================

impl Default for Settings {
    fn default() -> Self {
        Self {
            app: AppSettings::default(),
            window: WindowSettings::default(),
            keys: KeysSettings::default(),
            terminal: TerminalSettings::default(),
            linux: LinuxSettings::default(),
            polling: PollingSettings::default(),
            notifications: NotificationSettings::default(),
            claude: ClaudeSettings::default(),
            editor: EditorSettings::default(),
            worktree: WorktreeSettings::default(),
            work: WorkSettings::default(),
            reviews: ReviewsSettings::default(),
            web: WebSettings::default(),
            performance: PerformanceSettings::default(),
            accounts: BTreeMap::new(),
            oauth: OAuthSettings::default(),
            session_templates: default_session_templates(),
            tools: Vec::new(),
            triggers: Vec::new(),
            commands: Vec::new(),
            plugins: PluginsSettings::default(),
            env: BTreeMap::new(),
        }
    }
}

impl Settings {
    /// Compiled defaults (the `Default` layer).
    pub fn defaults() -> Self {
        Self::default()
    }
}

// =============================================================================================
// Project file `projects/<id>.toml` (SETTINGS §3)
// =============================================================================================

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct CodeHostBinding {
    pub account: AccountId,
    /// `"acme/shop"` | `"grp/sub/proj"`.
    pub repo: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct RepoConfig {
    pub id: String,
    /// `~` expanded.
    pub path: String,
    pub primary: bool,
    pub remote: String,
    pub base: String,
    pub code_host: Option<CodeHostBinding>,
}

impl Default for RepoConfig {
    fn default() -> Self {
        Self {
            id: String::new(),
            path: String::new(),
            primary: false,
            remote: "origin".into(),
            base: "main".into(),
            code_host: None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(deny_unknown_fields)]
pub struct ProjectV2Ref {
    pub owner: String,
    pub number: u32,
    #[serde(default = "default_status_field")]
    pub status_field: String,
}

fn default_status_field() -> String {
    "Status".into()
}

/// Tracker view; fields used depend on the account kind (SETTINGS §3).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct TrackerView {
    pub id: String,
    pub label: String,
    /// jira (required for jira).
    pub jql: Option<String>,
    /// jira: columns from board config when set.
    pub board_id: Option<u64>,
    /// redmine.
    pub project_id: Option<String>,
    /// redmine.
    pub query_id: Option<u64>,
    /// redmine: `me` (default) | `any`.
    pub assigned_to: Option<String>,
    /// redmine: `open` (default) | `closed` | `*`.
    pub status: Option<String>,
    /// github: `owner/name`.
    pub repo: Option<String>,
    /// github: search query.
    pub search: Option<String>,
    /// github Projects v2.
    pub project_v2: Option<ProjectV2Ref>,
    /// gitlab: `group/sub/proj`; gitea: `owner/name`; linear: project name.
    pub project: Option<String>,
    /// linear: team key (`ENG`).
    pub team: Option<String>,
    /// gitlab, gitea: `assigned_to_me` | `all`; linear: `assigned_to_me` (default) | `all`.
    pub scope: Option<String>,
    /// gitlab, gitea, linear (label names).
    pub labels: Option<Vec<String>>,
    /// gitlab scoped-label scope (default `workflow`).
    pub workflow_scope: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ColumnSpec {
    pub id: String,
    pub label: String,
    pub categories: Vec<StatusCategory>,
    pub names: Vec<String>,
}

/// `start` / `review` / `done` → TransitionTarget; overrides `work.on_*` targets.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct StatusMap {
    pub start: Option<TransitionTarget>,
    pub review: Option<TransitionTarget>,
    pub done: Option<TransitionTarget>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct RepoMatch {
    pub component: Option<String>,
    pub label: Option<String>,
    #[serde(rename = "type")]
    pub kind: Option<String>,
}

#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct RepoRule {
    #[serde(rename = "match")]
    pub r#match: RepoMatch,
    pub repo: String,
}

/// `[project.tracker]`.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct TrackerBinding {
    pub account: AccountId,
    pub views: Vec<TrackerView>,
    pub columns: Vec<ColumnSpec>,
    pub status_map: StatusMap,
    pub repo_rules: Vec<RepoRule>,
}

/// `[project]` table.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS, JsonSchema)]
#[serde(default, deny_unknown_fields)]
pub struct ProjectConfig {
    /// Must equal the file stem.
    pub id: ProjectId,
    pub name: String,
    pub color: Option<String>,
    /// 1-2 chars or sprite icon name.
    pub icon: Option<String>,
    pub default_template: Option<String>,
    pub repos: Vec<RepoConfig>,
    pub tracker: Option<TrackerBinding>,
}

/// Whole `projects/<id>.toml`: the `[project]` table plus project-scoped overrides of global keys.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, JsonSchema)]
#[schemars(title = "Kelta project")]
pub struct ProjectFile {
    pub project: ProjectConfig,
    #[serde(flatten)]
    pub overrides: Settings,
}

/// Repo-local `.kelta/config.toml` allowed top-level keys (SETTINGS §4).
pub const REPO_ALLOWED_KEYS: &[&str] = &[
    "tools",
    "triggers",
    "session_templates",
    "commands",
    "worktree.include",
    "worktree.setup",
    "worktree.setup_blocking",
    "worktree.branch_template",
    "env",
    "claude.append_system_prompt",
    "editor.review_args",
];

/// Repo-local keys that are inert until trusted (`x-kelta-exec`).
pub const REPO_EXEC_KEYS: &[&str] = &["tools", "triggers", "commands", "worktree.setup", "env"];

/// Runtime overrides (env `KELTA__SECTION__KEY=value`, CLI `--set key=value`, `--safe-graphics`, `--config-dir`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RuntimeOverrides {
    /// Dotted key → TOML value text, in application order.
    pub sets: Vec<(String, String)>,
    pub safe_graphics: bool,
    pub config_dir: Option<PathBuf>,
}

impl RuntimeOverrides {
    /// Collect `KELTA__A__B=value` env vars (keys lowercased, `__` → `.`) plus CLI args.
    pub fn from_env_and_cli(
        env: impl IntoIterator<Item = (String, String)>,
        cli: &crate::dirs::CliArgs,
    ) -> Self {
        let mut sets: Vec<(String, String)> = env
            .into_iter()
            .filter_map(|(k, v)| {
                k.strip_prefix("KELTA__").map(|rest| (rest.to_lowercase().replace("__", "."), v))
            })
            .collect();
        sets.sort();
        for kv in &cli.sets {
            if let Some((k, v)) = kv.split_once('=') {
                sets.push((k.trim().to_owned(), v.trim().to_owned()));
            }
        }
        Self { sets, safe_graphics: cli.safe_graphics, config_dir: cli.config_dir.clone() }
    }
}

/// `settings_effective` result.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS)]
pub struct EffectiveSettings {
    pub value: serde_json::Value,
    /// Dotted path → winning layer.
    pub sources: BTreeMap<String, Layer>,
}

/// `settings_layer_get` result.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize, TS)]
pub struct LayerDoc {
    pub path: PathBuf,
    pub value: serde_json::Value,
    pub text: String,
    /// Repo layer only.
    pub trusted: Option<bool>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct ValidationIssue {
    pub path: String,
    pub message: String,
    pub line: Option<u32>,
    pub col: Option<u32>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct TrustInfo {
    pub path: PathBuf,
    pub hash: String,
    pub trusted: bool,
}

/// Change notification from `ConfigService::watch` (→ `settings.changed`).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize, TS)]
pub struct SettingsDiff {
    pub layers: Vec<Layer>,
    pub paths: Vec<String>,
    pub requires_restart: Vec<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_serialize_and_parse_back() {
        let d = Settings::defaults();
        let v = serde_json::to_value(&d).unwrap();
        let back: Settings = serde_json::from_value(v).unwrap();
        assert_eq!(back, d);
        assert_eq!(d.terminal.max_live_views, 2);
        assert_eq!(d.editor.presets.len(), 6);
        assert_eq!(d.session_templates.len(), 5);
    }

    #[test]
    fn example_global_config_parses() {
        let text = r#"
[app]
theme = "system"

[window]
decorations = "auto"

[keys]
prefix = "ctrl+shift+space"
[keys.bindings]
"palette.open" = ["mod+k"]

[terminal]
font_family = "JetBrains Mono, monospace"
font_size = 13
renderer = "auto"
max_live_views = 4
shift_enter = { claude = "esc-cr", default = "passthrough" }
osc52 = "read-write"

[linux.graphics]
auto_nvidia = true

[notifications]
quiet_hours = "22:00-08:00"

[claude]
binary = "claude"
[claude.profiles.default]
model = "opus"
effort = "high"
permission_mode = "acceptEdits"

[editor]
default = "nvim"
follow_claude_edits = "reload"

[accounts.jira-acme]
kind = "jira"
base_url = "https://acme.atlassian.net"
email = "me@acme.com"
secret = "keyring:jira-acme"

[accounts.github-work]
kind = "github"
secret = "gh-cli"

[[tools]]
id = "lazydocker"
label = "Docker"
kind = "pty"
command = "lazydocker"
cwd = "{repo.path|project.root}"
check = ["lazydocker", "--version"]
install_hint = "brew install lazydocker"

[[tools]]
id = "isl"
label = "Sapling ISL"
kind = "web"
start = { command = "sl", args = ["web", "--no-open", "--foreground", "--json", "--port", "{port}", "--cwd", "{repo.path}"], ready = { stdout_json = "url" }, ready_timeout_ms = 10000, stop = { signal = "TERM", grace_ms = 3000 } }
embed = "auto"
url_is_secret = true

[[triggers]]
id = "claude-needs-me"
on = "session.status_changed"
match = { "payload.status" = ["needs_input", "waiting_user"], "session.visible" = false }
do = [ { action = "notify", title = "{project.name}", body = "{payload.preview}", urgency = "critical" } ]

[[triggers]]
id = "done-on-merge"
on = "pr.merged"
match = { "payload.linked_tickets" = "re:.+" }
do = [
  { action = "transition_ticket", to_category = "done" },
  { action = "prompt", text = "Remove worktree?", yes = [ { action = "command", id = "kelta.work.finish" } ] },
]

[plugins]
dev_paths = []
[plugins.sprint-burndown]
view_id = "sprint"
"#;
        let s: Settings = toml::from_str(text).unwrap();
        assert_eq!(s.terminal.osc52, Osc52::ReadWrite);
        assert_eq!(s.accounts.len(), 2);
        assert_eq!(s.triggers.len(), 2);
        assert!(s.plugins.settings.contains_key("sprint-burndown"));
        assert_eq!(s.claude.profiles["default"].permission_mode, PermissionMode::AcceptEdits);
    }

    #[test]
    fn example_project_file_parses() {
        let text = r##"
[project]
id = "shop"
name = "Shop"
color = "#e07a5f"
icon = "S"
default_template = "claude+editor"

[[project.repos]]
id = "api"
path = "~/code/shop-api"
primary = true
remote = "origin"
base = "main"
code_host = { account = "github-work", repo = "acme/shop-api" }

[project.tracker]
account = "jira-acme"
views = [
  { id = "mine", label = "My open", jql = "project = SHOP" },
]
columns = [
  { id = "todo", label = "To do", categories = ["todo"] },
  { id = "review", label = "Review", names = ["In Review", "Code Review"] },
]
status_map = { start = { category = "in_progress" }, review = { name = "In Review" }, done = { category = "done" } }
repo_rules = [ { match = { component = "frontend" }, repo = "web" } ]

[env]
DATABASE_URL = "postgres://localhost/shop_dev"
[worktree]
setup = ["pnpm install --frozen-lockfile"]
[claude.profiles.default]
model = "sonnet"
[[tools]]
id = "lazydocker"
enabled = true
"##;
        let p: ProjectFile = toml::from_str(text).unwrap();
        assert_eq!(p.project.id.as_str(), "shop");
        assert_eq!(p.overrides.worktree.setup.len(), 1);
        assert_eq!(p.overrides.claude.profiles["default"].model, "sonnet");
        let tracker = p.project.tracker.unwrap();
        assert_eq!(tracker.status_map.review, Some(TransitionTarget::Name { name: "In Review".into() }));
    }
}
