// Every Tauri command of ARCHITECTURE §6, in catalogue order.
// Shared by build.rs (app manifest → `allow-<command>` permissions) and tests that check
// `generate_handler!` and `capabilities/main.json` stay in sync. Keep this file free of `use`.

/// Command names (snake_case, as invoked from the UI).
pub const COMMANDS: &[&str] = &[
    // app
    "app_info",
    "app_ready",
    "bench_mark",
    "events_subscribe",
    "open_external",
    "perf_snapshot",
    "diagnostics_run",
    "clipboard_read",
    "clipboard_write",
    "notify_test",
    // settings
    "settings_schema",
    "settings_effective",
    "settings_layer_get",
    "settings_set",
    "settings_reset",
    "settings_validate",
    "settings_write_raw",
    "settings_open_file",
    "repo_trust",
    "secret_set",
    "secret_delete",
    "secret_backends_status",
    "secret_unlock",
    "oauth_device_start",
    "oauth_device_finish",
    "oauth_device_cancel",
    "account_test",
    // projects
    "project_list",
    "project_detect",
    "project_create",
    "project_update",
    "project_remove",
    "project_open",
    "project_close",
    "project_activate",
    "project_reorder",
    // layout
    "layout_get",
    "layout_save",
    // sessions
    "session_spawn",
    "session_spawn_template",
    "session_attach",
    "session_detach",
    "session_write",
    "session_resize",
    "session_ack",
    "session_kill",
    "session_restart",
    "session_rename",
    "session_list",
    "session_mark_seen",
    "session_link",
    "session_text_tail",
    "session_history_search",
    "terminal_set_palette",
    // tickets
    "tracker_list",
    "tracker_get",
    "tracker_columns",
    "tracker_transitions",
    "tracker_transition",
    "tracker_move",
    "tracker_comment",
    "tracker_assign",
    "tracker_search",
    // reviews
    "review_list",
    "review_get",
    "review_approve",
    "review_comment",
    "review_request_changes",
    // work
    "work_plan",
    "work_start",
    "work_list",
    "work_resume",
    "work_retry_step",
    "work_create_pr",
    "work_finish",
    "work_status",
    "work_pr_draft",
    "work_finish_merged",
    "work_check_prs",
    "work_send",
    "work_feedback",
    "work_rerequest_review",
    "work_resolve_sent_threads",
    "work_rebase",
    "work_push",
    "work_link",
    "work_status_all",
    "work_diff",
    "work_mark_reviewed",
    "work_set_note",
    "work_left",
    "editor_open",
    "editor_send_selection",
    "editor_quickfix",
    "fs_exists",
    // tools / plugins / triggers
    "tool_list",
    "tool_check",
    "tool_open",
    "tool_close",
    "plugin_list",
    "plugin_inspect",
    "plugin_install",
    "plugin_uninstall",
    "plugin_enable",
    "plugin_grant",
    "plugin_screen_open",
    "plugin_screen_close",
    "plugin_call",
    "command_run",
    "trigger_list",
    "trigger_test",
    "trigger_log",
];
