//! Test support (feature `testing`): fakes for every service trait, in-memory stores and fixtures.
//!
//! All fakes record what they receive and expose it through accessor methods; none spawns threads,
//! touches the network or arms timers.

mod core;
mod providers;
mod services;
mod stores;
mod terminal;

pub use self::core::FakeCore;
pub use self::providers::{FakeCodeHost, FakeTracker};
pub use self::services::{FakeSecrets, FakeSettings, FakeUiBridge};
pub use self::stores::{MemGrantStore, MemTrustStore, MemWorkStore};
pub use self::terminal::{FakeSpawned, FakeTerminalHost, RecordingSink, RecordingTerminalEvents};

/// JSON fixtures under `crates/kelta-proto/fixtures/` (one per DTO/event, generated by `xtask codegen`).
pub mod fixtures {
    use std::path::PathBuf;

    use serde::de::DeserializeOwned;

    use crate::error::KeltaError;

    /// Absolute fixtures directory.
    pub fn dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures")
    }

    /// Path of `<name>.json`.
    pub fn path(name: &str) -> PathBuf {
        dir().join(format!("{name}.json"))
    }

    /// Raw JSON of a fixture.
    pub fn load_value(name: &str) -> Result<serde_json::Value, KeltaError> {
        let text = std::fs::read_to_string(path(name))
            .map_err(|e| KeltaError::not_found(format!("fixture {name}: {e}")))?;
        Ok(serde_json::from_str(&text)?)
    }

    /// Deserialize `<name>.json` into `T`.
    pub fn load<T: DeserializeOwned>(name: &str) -> Result<T, KeltaError> {
        Ok(serde_json::from_value(load_value(name)?)?)
    }

    /// Every fixture name (sorted).
    pub fn names() -> Vec<String> {
        let mut out: Vec<String> = std::fs::read_dir(dir())
            .map(|rd| {
                rd.filter_map(|e| e.ok())
                    .filter_map(|e| {
                        let p = e.path();
                        (p.extension().and_then(|x| x.to_str()) == Some("json"))
                            .then(|| p.file_stem().and_then(|s| s.to_str()).map(str::to_owned))
                            .flatten()
                    })
                    .collect()
            })
            .unwrap_or_default();
        out.sort();
        out
    }
}
