//! `cargo run -p xtask -- codegen [--check]`
//!
//! Generates (all in memory first, then written or compared):
//! - `ui/src/lib/gen/**`: ts-rs types (+ `index.ts` barrel), `terminal_queries.ts`, `actions.ts`,
//!   `constants.ts`, `fixtures.ts` (typed fixture constants) and `fixtures.test.ts` (vitest)
//! - `schema/*.schema.json` (settings, project, tool, trigger, plugin-manifest)
//! - `crates/kelta-proto/fixtures/*.json` (one per DTO/event, from `kelta_proto::samples`)
//!
//! `--check` fails if any generated file differs, is missing, or is stale (a generated file that
//! would no longer be produced). Hand-written files in those directories are ignored.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{Context, Result, bail};
use serde_json::Value;

/// Marker present in every generated TS file (ts-rs writes its own note).
const TS_MARKER: &str = "Do not edit this file manually.";
const GEN_HEADER: &str =
    "// This file was generated by `cargo run -p xtask -- codegen`. Do not edit this file manually.\n";

const GEN_DIR: &str = "ui/src/lib/gen";
const SCHEMA_DIR: &str = "schema";
const FIXTURE_DIR: &str = "crates/kelta-proto/fixtures";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let result = match args.first().map(String::as_str) {
        Some("codegen") => codegen(args.iter().any(|a| a == "--check")),
        _ => {
            eprintln!("usage: cargo run -p xtask -- codegen [--check]");
            return ExitCode::from(2);
        }
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("xtask: {e:#}");
            ExitCode::FAILURE
        }
    }
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().map(Path::to_path_buf).unwrap_or_default()
}

/// A set of generated files owned by one directory.
struct Output {
    dir: &'static str,
    files: BTreeMap<String, String>,
    /// Is an existing file in `dir` one we generate (so it may be reported/removed as stale)?
    is_generated: fn(&Path, &str) -> bool,
}

fn codegen(check: bool) -> Result<()> {
    let root = repo_root();
    let outputs = vec![
        Output { dir: GEN_DIR, files: gen_ts()?, is_generated: |_, text| text.contains(TS_MARKER) },
        Output {
            dir: SCHEMA_DIR,
            files: gen_schemas()?,
            is_generated: |p, _| p.to_string_lossy().ends_with(".schema.json"),
        },
        Output {
            dir: FIXTURE_DIR,
            files: gen_fixtures()?,
            is_generated: |p, _| p.extension().is_some_and(|e| e == "json"),
        },
    ];

    let mut problems = Vec::new();
    let mut written = 0usize;
    for out in &outputs {
        let dir = root.join(out.dir);
        for (rel, content) in &out.files {
            let path = dir.join(rel);
            let current = std::fs::read_to_string(&path).ok();
            if current.as_deref() == Some(content.as_str()) {
                continue;
            }
            if check {
                problems.push(format!(
                    "{}: {}",
                    if current.is_some() { "differs" } else { "missing" },
                    path.strip_prefix(&root).unwrap_or(&path).display()
                ));
            } else {
                if let Some(parent) = path.parent() {
                    std::fs::create_dir_all(parent)?;
                }
                std::fs::write(&path, content).with_context(|| format!("writing {}", path.display()))?;
                written += 1;
            }
        }
        for stale in existing_files(&dir)? {
            let rel = stale.strip_prefix(&dir).unwrap_or(&stale).to_string_lossy().replace('\\', "/");
            if out.files.contains_key(&rel) {
                continue;
            }
            let text = std::fs::read_to_string(&stale).unwrap_or_default();
            if !(out.is_generated)(&stale, &text) {
                continue;
            }
            if check {
                problems.push(format!("stale: {}", stale.strip_prefix(&root).unwrap_or(&stale).display()));
            } else {
                std::fs::remove_file(&stale)?;
                written += 1;
            }
        }
    }

    if check {
        if !problems.is_empty() {
            for p in &problems {
                eprintln!("  {p}");
            }
            bail!(
                "generated code is out of date ({} files); run `cargo run -p xtask -- codegen`",
                problems.len()
            );
        }
        let total: usize = outputs.iter().map(|o| o.files.len()).sum();
        println!("codegen --check: {total} generated files up to date");
    } else {
        println!("codegen: {written} files written/removed");
    }
    Ok(())
}

fn existing_files(dir: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    if !dir.exists() {
        return Ok(out);
    }
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for e in std::fs::read_dir(&d)? {
            let p = e?.path();
            if p.is_dir() {
                stack.push(p);
            } else {
                out.push(p);
            }
        }
    }
    out.sort();
    Ok(out)
}

// =============================================================================================
// JSON helpers
// =============================================================================================

/// Recursively sort object keys so output does not depend on serde_json's `preserve_order`.
fn canonical(v: &Value) -> Value {
    match v {
        Value::Object(m) => {
            let sorted: BTreeMap<&String, Value> = m.iter().map(|(k, v)| (k, canonical(v))).collect();
            Value::Object(sorted.into_iter().map(|(k, v)| (k.clone(), v)).collect())
        }
        Value::Array(a) => Value::Array(a.iter().map(canonical).collect()),
        other => other.clone(),
    }
}

fn pretty(v: &Value) -> Result<String> {
    Ok(format!("{}\n", serde_json::to_string_pretty(&canonical(v))?))
}

/// Indent every line after the first by `n` spaces (embedding pretty JSON in TS).
fn indent(s: &str, n: usize) -> String {
    let pad = " ".repeat(n);
    s.trim_end().lines().enumerate().fold(String::new(), |mut acc, (i, l)| {
        if i > 0 {
            acc.push('\n');
            acc.push_str(&pad);
        }
        acc.push_str(l);
        acc
    })
}

fn js(v: &impl serde::Serialize) -> Result<String> {
    Ok(serde_json::to_string(v)?)
}

// =============================================================================================
// Schemas and fixtures
// =============================================================================================

fn gen_schemas() -> Result<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    for (name, schema) in kelta_proto::schema::all() {
        out.insert(name.to_owned(), pretty(&schema)?);
    }
    Ok(out)
}

fn gen_fixtures() -> Result<BTreeMap<String, String>> {
    let mut out = BTreeMap::new();
    for f in kelta_proto::samples::all() {
        let back =
            (f.roundtrip)(&f.value).map_err(|e| anyhow::anyhow!("{} ({}): {e}", f.name, f.type_name))?;
        if back != f.value {
            bail!("fixture {} ({}) does not round-trip", f.name, f.type_name);
        }
        out.insert(format!("{}.json", f.name), pretty(&f.value)?);
    }
    Ok(out)
}

// =============================================================================================
// TypeScript
// =============================================================================================

fn gen_ts() -> Result<BTreeMap<String, String>> {
    let mut out = kelta_proto::typescript::export_all().map_err(|e| anyhow::anyhow!("ts-rs: {e}"))?;
    // Barrel.
    let mut index = String::from(GEN_HEADER);
    index.push_str("// Barrel of every ts-rs type exported from kelta-proto.\n");
    for path in out.keys() {
        let module = path.trim_end_matches(".ts");
        let _ = writeln!(index, "export type * from './{module}';");
    }
    out.insert("index.ts".into(), index);
    out.insert("terminal_queries.ts".into(), gen_terminal_queries()?);
    out.insert("actions.ts".into(), gen_actions()?);
    out.insert("constants.ts".into(), gen_constants()?);
    let (fixtures, test) = gen_ts_fixtures()?;
    out.insert("fixtures.ts".into(), fixtures);
    out.insert("fixtures.test.ts".into(), test);
    Ok(out)
}

fn gen_terminal_queries() -> Result<String> {
    use kelta_proto::term::{QueryKind, SWALLOWED_QUERIES};
    let mut s = String::from(GEN_HEADER);
    s.push_str(
        "// Terminal queries answered by the Rust model (kelta_proto::term::SWALLOWED_QUERIES).\n\
         // xterm.js swallows exactly these (ARCHITECTURE §7.4): CSI via\n\
         // `term.parser.registerCsiHandler({ prefix, intermediates, final }, params => match)`,\n\
         // OSC via `term.parser.registerOscHandler(ident, data => data === '?')`.\n\n",
    );
    s.push_str(
        "export interface CsiQuery {\n  readonly name: string;\n  readonly prefix?: string;\n  \
         readonly intermediates?: string;\n  readonly final: string;\n  \
         /** Only swallow when the first param is one of these (empty = any). */\n  \
         readonly params: readonly number[];\n}\n\n",
    );
    s.push_str(
        "export interface OscQuery {\n  readonly name: string;\n  readonly ident: number;\n  \
         /** Only swallow the `?` query form. */\n  readonly queryOnly: boolean;\n}\n\n",
    );
    s.push_str("export const SWALLOWED_CSI: readonly CsiQuery[] = [\n");
    for q in SWALLOWED_QUERIES.iter().filter(|q| q.kind == QueryKind::Csi) {
        let mut fields = vec![format!("name: {}", js(&q.name)?)];
        if let Some(p) = q.prefix {
            fields.push(format!("prefix: {}", js(&p)?));
        }
        if let Some(i) = q.intermediates {
            fields.push(format!("intermediates: {}", js(&i)?));
        }
        fields.push(format!("final: {}", js(&q.final_byte.unwrap_or_default())?));
        fields.push(format!("params: {}", js(&q.params)?));
        let _ = writeln!(s, "  {{ {} }},", fields.join(", "));
    }
    s.push_str("];\n\nexport const SWALLOWED_OSC: readonly OscQuery[] = [\n");
    for q in SWALLOWED_QUERIES.iter().filter(|q| q.kind == QueryKind::Osc) {
        let _ = writeln!(
            s,
            "  {{ name: {}, ident: {}, queryOnly: {} }},",
            js(&q.name)?,
            q.osc.unwrap_or_default(),
            q.query_only
        );
    }
    s.push_str("];\n");
    Ok(s)
}

fn gen_actions() -> Result<String> {
    use kelta_proto::actions::{ACTIONS, PLUGIN_COMMAND_PREFIX, RESERVED_CHORDS, RESERVED_CLASSES};
    let mut s = String::from(GEN_HEADER);
    s.push_str(
        "// ActionId catalog with platform default chords (SPEC §4; kelta_proto::actions).\n\
         // `keys.bindings` in settings only overrides these defaults; `[]` unbinds.\n\n",
    );
    s.push_str("export const ACTION_IDS = [\n");
    for a in ACTIONS {
        let _ = writeln!(s, "  {},", js(&a.id)?);
    }
    s.push_str("] as const;\n\n");
    s.push_str("/** Built-in action ids; plugin commands use `plugin.command.<id>`. */\n");
    s.push_str("export type BuiltinActionId = (typeof ACTION_IDS)[number];\n");
    s.push_str("export type ActionId = BuiltinActionId | `plugin.command.${string}`;\n\n");
    s.push_str(
        "export type ActionContext = 'global' | 'ticket_views' | 'editor' | 'terminal' | 'external';\n\n",
    );
    s.push_str(
        "export interface ActionMeta {\n  readonly id: BuiltinActionId;\n  readonly label: string;\n  \
         readonly mac: readonly string[];\n  readonly linux: readonly string[];\n  \
         /** Key after the app-prefix (`keys.prefix`). */\n  readonly prefix: string | null;\n  \
         readonly context: ActionContext;\n}\n\n",
    );
    s.push_str("export const ACTIONS: readonly ActionMeta[] = [\n");
    for a in ACTIONS {
        let _ = writeln!(
            s,
            "  {{ id: {}, label: {}, mac: {}, linux: {}, prefix: {}, context: {} }},",
            js(&a.id)?,
            js(&a.label)?,
            js(&a.mac)?,
            js(&a.linux)?,
            js(&a.prefix)?,
            js(&a.context)?
        );
    }
    s.push_str("];\n\n");
    let _ = writeln!(s, "export const PLUGIN_COMMAND_PREFIX = {};\n", js(&PLUGIN_COMMAND_PREFIX)?);
    s.push_str("/** Chords never taken from the terminal (SPEC §4). */\n");
    let _ = writeln!(s, "export const RESERVED_CHORDS: readonly string[] = {};\n", js(&RESERVED_CHORDS)?);
    s.push_str(
        "/** Reserved chord classes: `ctrl+<letter>`, `alt+*`, `meta+*`, `ctrl+alt+*`, `super+*`. */\n",
    );
    let _ = writeln!(s, "export const RESERVED_CLASSES: readonly string[] = {};", js(&RESERVED_CLASSES)?);
    Ok(s)
}

fn gen_constants() -> Result<String> {
    use kelta_proto::{ctl, events, ext, hooks, term};
    let mut s = String::from(GEN_HEADER);
    s.push_str("// Protocol constants from kelta-proto.\n\n");
    s.push_str("/** Terminal channel frame tags (ARCHITECTURE §6.1). */\n");
    let _ = writeln!(s, "export const FRAME_DATA = {};", term::FRAME_DATA);
    let _ = writeln!(s, "export const FRAME_SNAPSHOT = {};", term::FRAME_SNAPSHOT);
    let _ = writeln!(s, "export const FRAME_EXIT = {};", term::FRAME_EXIT);
    let _ = writeln!(s, "export const FRAME_KEYBOARD = {};", term::FRAME_KEYBOARD);
    let _ = writeln!(s, "export const HIGH_WATERMARK = {};", term::HIGH_WATERMARK);
    let _ = writeln!(s, "export const LOW_WATERMARK = {};\n", term::LOW_WATERMARK);
    let _ = writeln!(s, "export const KELTA_API_VERSION = {};", js(&ext::KELTA_API_VERSION)?);
    let _ = writeln!(s, "export const CTL_PROTOCOL_VERSION = {};\n", ctl::CTL_PROTOCOL_VERSION);
    s.push_str("/** Bus event names (PLUGINS §6); external events use the `custom.` prefix. */\n");
    let _ = writeln!(
        s,
        "export const BUS_EVENTS = {} as const;",
        indent(&serde_json::to_string_pretty(events::bus::ALL)?, 0)
    );
    let _ = writeln!(s, "export const BLOCKING_BUS_EVENTS = {} as const;\n", js(&events::bus::BLOCKING)?);
    let methods: Vec<Value> =
        ext::PluginMethod::ALL.iter().map(|m| serde_json::to_value(m).unwrap_or(Value::Null)).collect();
    s.push_str("/** Plugin host API methods (PLUGINS §7). */\n");
    let _ = writeln!(
        s,
        "export const PLUGIN_METHODS = {} as const;\n",
        indent(&serde_json::to_string_pretty(&methods)?, 0)
    );
    let _ = writeln!(s, "export const HOOK_EVENTS = {} as const;", js(&hooks::names::ALL)?);
    Ok(s)
}

/// Rust type name of a fixture → TypeScript type.
fn ts_type(rust: &str) -> String {
    match rust.strip_prefix("Vec<").and_then(|r| r.strip_suffix('>')) {
        Some(inner) => format!("{}[]", ts_type(inner)),
        None => rust.to_owned(),
    }
}

fn camel(name: &str) -> String {
    let mut out = String::new();
    let mut up = false;
    for c in name.chars() {
        if c == '_' {
            up = true;
        } else if up {
            out.extend(c.to_uppercase());
            up = false;
        } else {
            out.push(c);
        }
    }
    out
}

fn gen_ts_fixtures() -> Result<(String, String)> {
    let fixtures = kelta_proto::samples::all();
    let mut types: Vec<String> =
        fixtures.iter().map(|f| ts_type(f.type_name).trim_end_matches("[]").to_owned()).collect();
    types.sort();
    types.dedup();

    let mut s = String::from(GEN_HEADER);
    s.push_str(
        "// Typed copies of crates/kelta-proto/fixtures/*.json. Type-checking this file (svelte-check /\n\
         // tsc) catches serde ↔ ts-rs drift; fixtures.test.ts round-trips them at runtime.\n\n",
    );
    let _ = writeln!(s, "import type {{ {} }} from './index';\n", types.join(", "));
    let mut names = Vec::new();
    for f in &fixtures {
        let ident = camel(f.name);
        let _ = writeln!(
            s,
            "export const {ident}: {} = {};\n",
            ts_type(f.type_name),
            indent(&serde_json::to_string_pretty(&canonical(&f.value))?, 0)
        );
        names.push((f.name, ident));
    }
    s.push_str("/** Every fixture by file stem. */\n");
    s.push_str("export const fixtures: Readonly<Record<string, unknown>> = {\n");
    for (name, ident) in &names {
        let _ = writeln!(s, "  {}: {ident},", js(name)?);
    }
    s.push_str("};\n");

    let mut t = String::from(GEN_HEADER);
    t.push_str(
        "import { describe, expect, it } from 'vitest';\n\nimport { fixtures } from './fixtures';\n\n\
         describe('kelta-proto fixtures', () => {\n  \
         it('has every fixture', () => {\n    \
         expect(Object.keys(fixtures).length).toBe(",
    );
    let _ = write!(t, "{}", names.len());
    t.push_str(
        ");\n  });\n\n  for (const [name, value] of Object.entries(fixtures)) {\n    \
         it(`${name} round-trips through JSON`, () => {\n      \
         expect(JSON.parse(JSON.stringify(value))).toEqual(value);\n    });\n  }\n});\n",
    );
    Ok((s, t))
}
